#setwd("D:/shiny_app_tests/appsilonApp")

library(readr)
library(dplyr)
library(stringr)
library(tools)
library(shiny)
library(xtable)
library(shinydashboard)
library(colourpicker)
library(leaflet)
library(shiny.semantic)
library(geosphere)
library(testit)
library(testthat)



# ships_sample <- read_csv("sample_ships.csv")
ships_sample <- read_csv("ships.csv")

ships_sample <- ships_sample %>% 
  select("SHIPNAME" ,"ship_type"  ,  "LAT"     ,    "LON" , DATETIME)


#getting the list of vessels type and names
list_of_vessel_type <-
  sort(c(unique(ships_sample$ship_type)))


#Function which calculates the distance in KM between 2 points 
earth.dist <- function (long1, lat1, long2, lat2)
{
  rad <- pi/180
  a1 <- lat1 * rad
  a2 <- long1 * rad
  b1 <- lat2 * rad
  b2 <- long2 * rad
  dlon <- b2 - a2
  dlat <- b1 - a1
  a <- (sin(dlat/2))^2 + cos(a1) * cos(b1) * (sin(dlon/2))^2
  c <- 2 * atan2(sqrt(a), sqrt(1 - a))
  R <- 6378.145
  d <- R * c *1000
  return(d)
}


#gets a vessel type and name, and returns a DF filtered with the vessel type and name
#In addition a few more variables are created:
#lags of longitude and latitude, and the distance between 2 consecutive observations
#the DF which is returned is sorted in descending order by distance travelled and the date 
df_summary_fun <- function(typeVes, nameVes) {
  ships_sample %>% 
    filter(ship_type == typeVes & SHIPNAME == nameVes) %>% 
    dplyr::arrange(DATETIME) %>% 
    mutate(lag_LAT = lag(LAT, default = first(LAT)),
           lag_LON = lag(LON, default = first(LON)),
           distanceMeters = base::round(earth.dist(long1 = lag_LON, lat1 = lag_LAT, long2 = LON, lat2 = LAT)),digits =2 ) %>% 
    dplyr::arrange(desc(distanceMeters, DATETIME)) %>% 
    select("SHIPNAME" ,"ship_type"  ,  "LAT"     ,    "LON" , "lag_LAT"   ,  "lag_LON"  , "distanceMeters" )
}


data_table_fun <- function(typeVes, nameVes) {
  myTable  <-     df_summary_fun(typeVes, nameVes)
  
  colnames(myTable) <- c("Ship Name" , "Ship Type", "Latitude", "Longitude", "Lag Latitude", "Lag Longitude", "Distance travelled (M)")
  
  myTable <- myTable %>% 
    select("Latitude", "Longitude", "Lag Latitude", "Lag Longitude", "Distance travelled (M)")
  
  myTable <- myTable[1:5,]
  
  myTable%>%
    DT::datatable(rownames= FALSE, options = list(
      iDisplayLength = 1,
      aLengthMenu = c(1, 5),
      dom = 'ltp'
    )) %>%
    DT::formatStyle(-5, color = '#15354a', fontWeight = 'normal')
}

#gets the DF which was generated by 'df_summary_fun' and returns the total distance
#travelled for a specific ship
totalDistFun <- function(typeVes, nameVes) {
  myTable  <-     df_summary_fun(typeVes, nameVes)
  sum(myTable[["distanceMeters"]])
}


# function which take the vessel type and name, and return the coordinates of start movement, end movement 
startEndFun <- function(typeVas, nameVas) {
  
  myData  <-  ships_sample %>% 
    filter(ship_type == typeVas & SHIPNAME == nameVas) %>% 
    dplyr::arrange(DATETIME) %>% 
    select( "LON" ,"LAT")
  
  myData[c(1,nrow(myData)),]
}





ui <- semanticPage(
  
  h1(id="big-heading", "Appsilon Task"),
  tags$style(HTML("#big-heading{color: #15354a;font-size: 20px;}")),
  
  sidebar_layout(
    sidebar_panel(
      shiny::selectInput(inputId = "ves_type_input",label =  "Select vessel type:",choices = list_of_vessel_type ,selected = list_of_vessel_type[1]),
      shiny::selectInput(inputId = "ves_name_input",label =  "Select vessel name:",choices = NULL ),
      DT::dataTableOutput("dtsummary", width = 0.5, height = 0.5),
      width = 2
    ),
    
    
    
    main_panel(
      textOutput("txt"),
      tags$head(tags$style("#txt{color: #15354a;
                                 font-size: 15px;
                                 
                                 }"
      )
      ),
      textOutput("txt2"),
      tags$head(tags$style("#txt2{color: #15354a;
                                 font-size: 14px;
                                 
                                 }"
      )
      ),
      
      leaflet::leafletOutput("map", width = "75%", height = "500px")
      
    ),
    mirrored = F
    
  )
)
server <- function(input, output,session) {
  
  ves_type_input <- reactive({
    filter(ships_sample, ship_type == input$ves_type_input)
  })
  
  observeEvent(ves_type_input(), {
    choicesss <- sort(unique(ves_type_input()$SHIPNAME))
    shiny::updateSelectInput(session, inputId = "ves_name_input", choices = choicesss) 
  })
  
  customer <- reactive({
    req(input$ves_name_input)
    filter(ves_type_input(), SHIPNAME == input$ves_name_input)
  })
  
  data_table_summary <- reactive ({
    data_table_fun(
      input$ves_type_input,
      input$ves_name_input)
  })
  
  output$dtsummary <- DT::renderDT({
    data_table_summary()
  })
  
  startEnd <- reactive ({
    as.matrix(
      startEndFun(
        input$ves_type_input,
        input$ves_name_input))
  })
  
  
  
  
  output$map <-renderLeaflet({
    leaflet() %>%
      addProviderTiles(providers$Stamen.TonerLite,
                       options = providerTileOptions(noWrap = TRUE)
      ) %>% 
      addMarkers(data = startEnd(),popup = c("start","end"))
  })
  
  output$txt <- renderText({
    
    myMat<- as.matrix(startEndFun(typeVas = input$ves_type_input, nameVas = input$ves_name_input))
    res <-distm(c(myMat[1,1],myMat[1,2]),c(myMat[2,1],myMat[2,2]))
    as.character(paste0( input$ves_name_input, ": The direct ditance between starting and end points is " , base::formatC(round(res, 2),big.mark=",", format="d")," meters",""))
    
  })
  
  output$txt2 <- renderText({
    
    totalDist <- totalDistFun(typeVes = input$ves_type_input,nameVes =  input$ves_name_input)
    as.character(paste0("The total travel distance between the two points is " , base::formatC(round(totalDist, 2),big.mark=",", format="d")," meters",""))
    
    
    
  })
  
  
}
shinyApp(ui, server)
